---

apiVersion: v1
kind: ConfigMap

metadata:
  name: tgbotserver
  namespace: {{ $.Release.Namespace }}

data:
  TELEGRAM_API_ID: "{{ $.Values.TgBotServerApiId }}"
  TELEGRAM_API_HASH: "{{ $.Values.TgBotServerApiHash }}"

