{{ if $.Values.IngressDomain -}}

---

apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-telegram-org"
spec:
  type: "ExternalName"
  externalName: "api.telegram.org"
  ports:
    - name: "https"
      port: 443
      targetPort: 443

---

apiVersion: "networking.k8s.io/v1"
kind: "Ingress"

metadata:
  name: "tgbotserver"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "333"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "333"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: api.telegram.org
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"

spec:
  ingressClassName: "nginx"

  tls:
  - hosts:
    - "{{ $.Values.IngressDomain }}"

  rules:
  - host: "{{ $.Values.IngressDomain }}"
    http:
      paths:
      - path: "/"
        pathType: "Prefix"
        backend:
          service:
            name: "api-telegram-org"
            port:
              number: 443

{{ end }}

