---

apiVersion: v1
kind: Service

metadata:
  name: tgbotserver
  namespace: {{ $.Release.Namespace }}
  labels:
    app: tgbotserver

spec:
  selector:
    app: tgbotserver
  type: ClusterIP
  ports:
    - port: 80


