---

apiVersion: "apps/v1"
kind: "StatefulSet"

metadata:
  name: "tgbotserver"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: "tgbotserver"

spec:
  selector:
    matchLabels:
      app: "tgbotserver"

  template:
    metadata:
      name: "tgbotserver"
      labels:
        app: "tgbotserver"
      annotations:
        image: "{{ $.Values.ImageNameGithubTgBotServer }}:{{ $.Values.ImageTagGithubTgBotServer }}"

    spec:

      volumes:
        - name: "tgbotserver"
          hostPath:
            path: "/opt/tgbotserver/"
            type: "DirectoryOrCreate"

      containers:

        - name: "tgbotserver"
          image: "{{ $.Values.ImageNameGithubTgBotServer }}:{{ $.Values.ImageTagGithubTgBotServer }}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              name: api
            - containerPort: 8080
              name: stats
          env:
            - name: "TELEGRAM_API_ID"
              value: "{{ $.Values.TgBotServerApiId }}"
            - name: "TELEGRAM_API_HASH"
              value: "{{ $.Values.TgBotServerApiHash }}"
          command: ["/tgbotserver/tgbotserver", "--http-port=80", "--http-stat-port=8080" {{- if $.Values.OptionLocal-}} , "--local" {{-end-}} ]
          volumeMounts:
            - name: "tgbotserver"
              mountPath: "/tgbotserver/downloads/"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 3


