apiVersion: "v2"
name: "helm.tgbotserver"
description: "Telegram Bot API server"
type: "application"
version: "__VERSION__"
appVersion: "__VERSION__"
home: "https://github.com/shoce/tgbotserver/tree/main/helm/"

