---

DEBUG: false

ImageNameGithubTgBotServer: "ghcr.io/shoce/tgbotserver-arm64"
ImageTagGithubTgBotServer: ""

TgBotServerApiId: ""
TgBotServerApiHash: ""

OptionLocal: true

IngressDomain: ""
IngressProxyAll: false

IngressRouteDomain: ""
IngressRouteProxyAll: false

